---

- name: Configure OSPF
  hosts: switch[0]

  vars_files:
  - cli_vault.yml

  tasks:
    - name: Create vrouter
      pn_vrouter_creation:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        #pn_loopback_ip: '10.10.10.10'
        #pn_vrrp_id: '18'
        pn_switch_list: "{{ groups['switch'] }}"

    - name: Configure OSPF
      pn_ospf_configuration:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_ospf_data: "{{ lookup('file', '{{ ospf_file }}') }}"
        pn_switch_list: "{{ groups['switch'] }}"
