---

- name: Configure eBGP, SVI
  hosts: all

  vars_files:
  - cli_vault.yml

  vars:
  - bgp_file: /etc/ansible/pluribus-ansible/ansible/bgp.csv
  - vlan_file: /etc/ansible/pluribus-ansible/ansible/vlan.csv
  - svi_file: /etc/ansible/pluribus-ansible/ansible/svi.csv

  tasks:
    - name: Create vlans
      pn_vlan_creation:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_switch: "{{ inventory_hostname }}"
        pn_vlan_data: "{{ lookup('file', '{{ vlan_file }}') }}"

    - name: Configure eBGP
      pn_ebgp_configuration:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_switch: "{{ inventory_hostname }}"
        pn_bgp_data: "{{ lookup('file', '{{ bgp_file }}') }}"

    - name: Configure SVI
      pn_svi_configuration:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_switch: "{{ inventory_hostname }}"
        pn_svi_data: "{{ lookup('file', '{{ svi_file }}') }}"
