---

- name: Configure OSPF
  hosts: all

  vars_files:
  - cli_vault.yml

  vars:
  - ospf_file: /etc/ansible/pluribus-ansible/ansible/ospf.csv
  - vrouter_file: /etc/ansible/pluribus-ansible/ansible/vrouter.csv

  tasks:
    - name: Create vrouter
      pn_vrouter_creation:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_vrouter_data: "{{ lookup('file', '{{ vrouter_file }}') }}"

    - name: Configure OSPF
      pn_ospf_configuration:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_ospf_data: "{{ lookup('file', '{{ ospf_file }}') }}"
        pn_switch_list: "{{ groups['switch'] }}"
